require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
    NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'spec/fixtures/*.rb'

Lint/DuplicateMethods:
  Exclude:
    - 'spec/fixtures/*.rb'

RSpec/FilePath:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Performance/TimesMap:
  Exclude:
    - 'spec/**/**.rb'
